interface ColorsType {
    name: string;
    hex: string;
    shades: Array<{ color: string; shade: number; selected: boolean }>;
}

// create type for colors
type possibleColors = "" | "primary" | "gray" | "red" | "orange" | "amber" | "yellow" | "lime" | "green" | "emerald" | "teal" | "cyan" | "lightBlue" | "blue" | "indigo" | "violet" | "purple" | "fuchsia" | "pink" | "rose" | "warmGray" | "trueGray" | "coolGray" | "blueGray";



let colorList = [
    {
        name: 'gray',
        hex: '#a5a5a5',
        shades: [
            { hex: '#f3f4f6', shade: 100, selected: false },
            { hex: '#e5e7eb', shade: 200, selected: false },
            { hex: '#d1d5db', shade: 300, selected: false },
            { hex: '#9ca3af', shade: 400, selected: false },
            { hex: '#6b7280', shade: 500, selected: false },
            { hex: '#3d3d3d', shade: 600, selected: false },
            { hex: '#1f1f1f', shade: 700, selected: false },
            { hex: '#101010', shade: 800, selected: false },
            { hex: '#000000', shade: 900, selected: false },
        ],
    },
    {
        name: 'red',
        hex: '#ef4444',
        shades: [
            { hex: '#fee2e2', shade: 100, selected: false },
            { hex: '#fecaca', shade: 200, selected: false },
            { hex: '#fca5a5', shade: 300, selected: false },
            { hex: '#f87171', shade: 400, selected: false },
            { hex: '#ef4444', shade: 500, selected: false },
            { hex: '#dc2626', shade: 600, selected: false },
            { hex: '#b91c1c', shade: 700, selected: false },
            { hex: '#991b1b', shade: 800, selected: false },
            { hex: '#7f1d1d', shade: 900, selected: false },
        ],
    },
    {
        name: 'orange',
        hex: '#fb923c',
        shades: [
            { hex: '#ffedd5', shade: 100, selected: false },
            { hex: '#fed7aa', shade: 200, selected: false },
            { hex: '#fdba74', shade: 300, selected: false },
            { hex: '#fb923c', shade: 400, selected: false },
            { hex: '#f97316', shade: 500, selected: false },
            { hex: '#ea580c', shade: 600, selected: false },
            { hex: '#c2410c', shade: 700, selected: false },
            { hex: '#9a3412', shade: 800, selected: false },
            { hex: '#7c2d12', shade: 900, selected: false },
        ],
    },
    {
        name: 'amber',
        hex: '#fbbf24',
        shades: [
            { hex: '#fef3c7', shade: 100, selected: false },
            { hex: '#fde68a', shade: 200, selected: false },
            { hex: '#fcd34d', shade: 300, selected: false },
            { hex: '#fbbf24', shade: 400, selected: false },
            { hex: '#f59e0b', shade: 500, selected: false },
            { hex: '#d97706', shade: 600, selected: false },
            { hex: '#b45309', shade: 700, selected: false },
            { hex: '#92400e', shade: 800, selected: false },
            { hex: '#78350f', shade: 900, selected: false },
        ],
    },
    {
        name: 'yellow',
        hex: '#facc15',
        shades: [
            { hex: '#fef9c3', shade: 100, selected: false },
            { hex: '#fef08a', shade: 200, selected: false },
            { hex: '#fde047', shade: 300, selected: false },
            { hex: '#facc15', shade: 400, selected: false },
            { hex: '#eab308', shade: 500, selected: false },
            { hex: '#ca8a04', shade: 600, selected: false },
            { hex: '#a16207', shade: 700, selected: false },
            { hex: '#854d0e', shade: 800, selected: false },
            { hex: '#713f12', shade: 900, selected: false },
        ],
    },
    {
        name: 'lime',
        hex: '#a3e635',
        shades: [
            { hex: '#ecfccb', shade: 100, selected: false },
            { hex: '#d9f99d', shade: 200, selected: false },
            { hex: '#bef264', shade: 300, selected: false },
            { hex: '#a3e635', shade: 400, selected: false },
            { hex: '#84cc16', shade: 500, selected: false },
            { hex: '#65a30d', shade: 600, selected: false },
            { hex: '#4d7c0f', shade: 700, selected: false },
            { hex: '#3f6212', shade: 800, selected: false },
            { hex: '#365314', shade: 900, selected: false },
        ],
    },
    {
        name: 'green',
        hex: '#4ade80',
        shades: [
            { hex: '#dcfce7', shade: 100, selected: false },
            { hex: '#bbf7d0', shade: 200, selected: false },
            { hex: '#86efac', shade: 300, selected: false },
            { hex: '#4ade80', shade: 400, selected: false },
            { hex: '#22c55e', shade: 500, selected: false },
            { hex: '#16a34a', shade: 600, selected: false },
            { hex: '#15803d', shade: 700, selected: false },
            { hex: '#166534', shade: 800, selected: false },
            { hex: '#14532d', shade: 900, selected: false },
        ],
    },
    {
        name: 'emerald',
        hex: '#34d399',
        shades: [
            { hex: '#d1fae5', shade: 100, selected: false },
            { hex: '#a7f3d0', shade: 200, selected: false },
            { hex: '#6ee7b7', shade: 300, selected: false },
            { hex: '#34d399', shade: 400, selected: false },
            { hex: '#10b981', shade: 500, selected: false },
            { hex: '#059669', shade: 600, selected: false },
            { hex: '#047857', shade: 700, selected: false },
            { hex: '#065f46', shade: 800, selected: false },
            { hex: '#064e3b', shade: 900, selected: false },
        ],
    },
    {
        name: 'teal',
        hex: '#2dd4bf',
        shades: [
            { hex: '#ccfbf1', shade: 100, selected: false },
            { hex: '#99f6e4', shade: 200, selected: false },
            { hex: '#5eead4', shade: 300, selected: false },
            { hex: '#2dd4bf', shade: 400, selected: false },
            { hex: '#14b8a6', shade: 500, selected: false },
            { hex: '#0d9488', shade: 600, selected: false },
            { hex: '#0f766e', shade: 700, selected: false },
            { hex: '#115e59', shade: 800, selected: false },
            { hex: '#134e4a', shade: 900, selected: false },
        ],
    },
    {
        name: 'cyan',
        hex: '#22d3ee',
        shades: [
            { hex: '#cffafe', shade: 100, selected: false },
            { hex: '#a5f3fc', shade: 200, selected: false },
            { hex: '#67e8f9', shade: 300, selected: false },
            { hex: '#22d3ee', shade: 400, selected: false },
            { hex: '#06b6d4', shade: 500, selected: false },
            { hex: '#0891b2', shade: 600, selected: false },
            { hex: '#0e7490', shade: 700, selected: false },
            { hex: '#155e75', shade: 800, selected: false },
            { hex: '#164e63', shade: 900, selected: false },
        ],
    },
    {
        name: 'sky',
        hex: '#38bdf8',
        shades: [
            { hex: '#e0f2fe', shade: 100, selected: false },
            { hex: '#bae6fd', shade: 200, selected: false },
            { hex: '#7dd3fc', shade: 300, selected: false },
            { hex: '#38bdf8', shade: 400, selected: false },
            { hex: '#0ea5e9', shade: 500, selected: false },
            { hex: '#0284c7', shade: 600, selected: false },
            { hex: '#0369a1', shade: 700, selected: false },
            { hex: '#075985', shade: 800, selected: false },
            { hex: '#0c4a6e', shade: 900, selected: false },
        ],
    },
    {
        name: 'blue',
        hex: '#60a5fa',
        shades: [
            { hex: '#dbeafe', shade: 100, selected: false },
            { hex: '#bfdbfe', shade: 200, selected: false },
            { hex: '#93c5fd', shade: 300, selected: false },
            { hex: '#60a5fa', shade: 400, selected: false },
            { hex: '#3b82f6', shade: 500, selected: false },
            { hex: '#2563eb', shade: 600, selected: false },
            { hex: '#1d4ed8', shade: 700, selected: false },
            { hex: '#1e40af', shade: 800, selected: false },
            { hex: '#1e3a8a', shade: 900, selected: false },
        ],
    },
    {
        name: 'indigo',
        hex: '#818cf8',
        shades: [
            { hex: '#e0e7ff', shade: 100, selected: false },
            { hex: '#c7d2fe', shade: 200, selected: false },
            { hex: '#a5b4fc', shade: 300, selected: false },
            { hex: '#818cf8', shade: 400, selected: false },
            { hex: '#6366f1', shade: 500, selected: false },
            { hex: '#4f46e5', shade: 600, selected: false },
            { hex: '#4338ca', shade: 700, selected: false },
            { hex: '#3730a3', shade: 800, selected: false },
            { hex: '#312e81', shade: 900, selected: false },
        ],
    },
    {
        name: 'violet',
        hex: '#a78bfa',
        shades: [
            { hex: '#ede9fe', shade: 100, selected: false },
            { hex: '#ddd6fe', shade: 200, selected: false },
            { hex: '#c4b5fd', shade: 300, selected: false },
            { hex: '#a78bfa', shade: 400, selected: false },
            { hex: '#8b5cf6', shade: 500, selected: false },
            { hex: '#7c3aed', shade: 600, selected: false },
            { hex: '#6d28d9', shade: 700, selected: false },
            { hex: '#5b21b6', shade: 800, selected: false },
            { hex: '#4c1d95', shade: 900, selected: false },
        ],
    },
    {
        name: 'purple',
        hex: '#c084fc',
        shades: [
            { hex: '#f3e8ff', shade: 100, selected: false },
            { hex: '#e9d5ff', shade: 200, selected: false },
            { hex: '#d8b4fe', shade: 300, selected: false },
            { hex: '#c084fc', shade: 400, selected: false },
            { hex: '#a855f7', shade: 500, selected: false },
            { hex: '#9333ea', shade: 600, selected: false },
            { hex: '#7e22ce', shade: 700, selected: false },
            { hex: '#6b21a8', shade: 800, selected: false },
            { hex: '#581c87', shade: 900, selected: false },
        ],
    },
    {
        name: 'fuchsia',
        hex: '#e879f9',
        shades: [
            { hex: '#fae8ff', shade: 100, selected: false },
            { hex: '#f5d0fe', shade: 200, selected: false },
            { hex: '#f0abfc', shade: 300, selected: false },
            { hex: '#e879f9', shade: 400, selected: false },
            { hex: '#d946ef', shade: 500, selected: false },
            { hex: '#c026d3', shade: 600, selected: false },
            { hex: '#a21caf', shade: 700, selected: false },
            { hex: '#86198f', shade: 800, selected: false },
            { hex: '#701a75', shade: 900, selected: false },
        ],
    },
    {
        name: 'pink',
        hex: '#f472b6',
        shades: [
            { hex: '#fce7f3', shade: 100, selected: false },
            { hex: '#fbcfe8', shade: 200, selected: false },
            { hex: '#f9a8d4', shade: 300, selected: false },
            { hex: '#f472b6', shade: 400, selected: false },
            { hex: '#ec4899', shade: 500, selected: false },
            { hex: '#db2777', shade: 600, selected: false },
            { hex: '#be185d', shade: 700, selected: false },
            { hex: '#9d174d', shade: 800, selected: false },
            { hex: '#831843', shade: 900, selected: false },
        ],
    },
    {
        name: 'rose',
        hex: '#fb7185',
        shades: [
            { hex: '#ffe4e6', shade: 100, selected: false },
            { hex: '#fecdd3', shade: 200, selected: false },
            { hex: '#fda4af', shade: 300, selected: false },
            { hex: '#fb7185', shade: 400, selected: false },
            { hex: '#f43f5e', shade: 500, selected: false },
            { hex: '#e11d48', shade: 600, selected: false },
            { hex: '#be123c', shade: 700, selected: false },
            { hex: '#9f1239', shade: 800, selected: false },
            { hex: '#881337', shade: 900, selected: false },
        ],
    },
];

export { colorList, ColorsType, possibleColors };
